export * from './audioApi.service';
import { AudioApiService } from './audioApi.service';
export * from './campaignApi.service';
import { CampaignApiService } from './campaignApi.service';
export * from './discordInfoApi.service';
import { DiscordInfoApiService } from './discordInfoApi.service';
export * from './helloWorldApi.service';
import { HelloWorldApiService } from './helloWorldApi.service';
export * from './sceneApi.service';
import { SceneApiService } from './sceneApi.service';
export * from './scheduledCampaignApi.service';
import { ScheduledCampaignApiService } from './scheduledCampaignApi.service';
export * from './tagApi.service';
import { TagApiService } from './tagApi.service';
export * from './trackApi.service';
import { TrackApiService } from './trackApi.service';
export * from './trackPropertyApi.service';
import { TrackPropertyApiService } from './trackPropertyApi.service';
export const APIS = [AudioApiService, CampaignApiService, DiscordInfoApiService, HelloWorldApiService, SceneApiService, ScheduledCampaignApiService, TagApiService, TrackApiService, TrackPropertyApiService];
