/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DiscordVoiceChannelDto } from './discordVoiceChannelDto';
import { DiscordVoiceStatusDTO } from './discordVoiceStatusDTO';


export interface DiscordStatusDTO { 
    voiceStatus?: DiscordVoiceStatusDTO;
    voiceChannels?: Array<DiscordVoiceChannelDto>;
}

