/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DiscordVoiceStatusDTO { 
    currentlyPlaying?: string;
    joinedAudioChannel?: string;
    joinedUsers?: Array<string>;
    trackDuration?: number;
    trackPosition?: number;
}

