/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TrackEntity } from './trackEntity';


export interface SceneEntity { 
    id?: number;
    title?: string;
    introTrack?: TrackEntity;
    moodTags?: Array<string>;
}

