/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CampaignEntity } from './campaignEntity';


export interface ScheduledCampaignEntity { 
    id?: number;
    campaign?: CampaignEntity;
    date?: string;
}

