/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TagEntity { 
    id?: number;
    name?: string;
    selectionMethod?: TagEntity.SelectionMethodEnum;
}
export namespace TagEntity {
    export const SelectionMethodEnum = {
        Normal: 'Normal',
        OnlyIfSelfOrRelatedSpecified: 'OnlyIfSelfOrRelatedSpecified',
        OnlyIfSelfSpecified: 'OnlyIfSelfSpecified'
    } as const;
    export type SelectionMethodEnum = typeof SelectionMethodEnum[keyof typeof SelectionMethodEnum];
}


