/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { YoutubeTrackInfoEntity } from './youtubeTrackInfoEntity';


export interface TrackEntity { 
    id?: number;
    title?: string;
    artist?: string;
    youtube?: YoutubeTrackInfoEntity;
    tags?: Array<string>;
}

