/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TrackPropertyTypeEntity } from './trackPropertyTypeEntity';


export interface TrackPropertyValueEntity { 
    id?: number;
    propertyType?: TrackPropertyTypeEntity;
    value?: number;
}

